### ISSUE TITLE
Messed up colors

### ISSUE THREAD

**Issue by bjorn3** [NerdyPepper/eva#43] opened 2020-11-04 18:36 UTC
`log(1+2)`

![image](https://user-images.githubusercontent.com/17426603/98154221-beec7680-1ed4-11eb-8b02-967df82bbc01.png)

backspace

![image](https://user-images.githubusercontent.com/17426603/98154273-d62b6400-1ed4-11eb-90d8-96d971f55220.png)

backspace

![image](https://user-images.githubusercontent.com/17426603/98154318-e6dbda00-1ed4-11eb-9b59-53145d81547c.png)

`2`

![image](https://user-images.githubusercontent.com/17426603/98154367-f5c28c80-1ed4-11eb-9ed8-0b972045fdce.png)

backspace backspace

![image](https://user-images.githubusercontent.com/17426603/98154413-08d55c80-1ed5-11eb-9c8b-339bd3b3cf77.png)

**Comment by pickfire** [comment] 2020-11-05 02:22
The behavior is correct except for the first one, there seemed to have no color for the first line, not sure why is that.

The forth one supposed to have color and I don't have issue that here. 
![Screenshot_20201105_102001](https://user-images.githubusercontent.com/4687791/98189709-7c687f80-1f50-11eb-9a42-a3a2a782267e.png)

For second one, it is correct because `)` will be auto-filled so even if you pressed enter it will work.

For the third one, it is correct to be red, because it cannot end with `+`.

For the forth one, I cannot reproduce, the color is incorrect.

For the fifth one, it is correct, the right parenthesis should be auto-filled.

**Comment by oppiliappan** [comment] 2020-11-06 15:27
Thanks for the quick review @pickfire!

@bjorn3 I am aware of the coloring issues, they are unfortunately creeping into eva from rustyline, maybe a revisit to the highlighting code and an upgrade to the latest rustyline could fix this.

**Comment by pickfire** [comment] 2022-06-24 17:20
Thanks for filling up the issue @bjorn3, the latest master branch no longer have this issue. And I will do a release for 0.3 soon so will be closing this for now.

**Closed as completed by pickfire** 2022-06-24 17:20 UTC
